# -*- Mode: Eagle -*-
#
# Sample drill rack file.
#
# drill_size is the size of the drill bit.
# minimum is the smallest hole the bit will be used for.
# maximum is the largest hole the bit will be used for.
#
# Each value can have a "unit of measure" added to it,
# such as 0.500mm . If you do not provide the unit of measure,
# values over 0.250 are considered millimeters, and
# values under 0.250 are considered inches. For example:
# 0.400 would be considered 0.400 mm.
# 0.125 would be considered 0.125 inches.
#
# Please note that you must use a TAB character
# between each setting on a line.
# 
# Tip: Set the TAB size of your editor to 12 characters.
#
tool	drill_size	minimum	maximum	length
T01	0.900mm	0.000mm	1.100mm	5.000mm
T03	1.500mm	1.101mm	1.500mm	5.000mm
T04	2.000mm	1.501mm	2.000mm	5.000mm
T05	2.500mm	2.001mm	2.500mm	5.000mm
T06	3.000mm	2.501mm	3.000mm	5.000mm
T07	3.175mm	3.001mm	5.000mm	5.000mm
